'use client';

import 'bootstrap/dist/css/bootstrap.css';
import "bootstrap/dist/js/bootstrap.bundle.min";
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar';


const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Raiyan Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,

}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        {/* <span className='text-dark'><Link href="/login">Go To Login</Link> </span>
        <Link href="/signup">Go To Sign Up</Link>
         */}


      </body>
    </html>
  )
}
